[app]
name = "mflow"
key  = "this is your app key"

[http]
host = "127.0.0.1"
port = 8090

[grpc]
host = "127.0.0.1"
port = 18090

[mcenter]
address = "127.0.0.1:18010"
client_id = "ZvsVVuRSI8teTBPahcINlDnw"
client_secret = "C7MP1auMriB6TQGhMf40zcNrqfVeYGbQ"

[mongodb]
endpoints = ["127.0.0.1:27017"]
database = "mflow"

[log]
level = "debug"

[log.file]
enable = true

[trace]
enable = false
endpoint = "127.0.0.1:4318"