// Code generated by github.com/infraboard/mcube/v2
// DO NOT EDIT

package task

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseSORT_TYPEFromString Parse SORT_TYPE from string
func ParseSORT_TYPEFromString(str string) (SORT_TYPE, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := SORT_TYPE_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown SORT_TYPE: %s", str)
	}

	return SORT_TYPE(v), nil
}

// Equal type compare
func (t SORT_TYPE) Equal(target SORT_TYPE) bool {
	return t == target
}

// IsIn todo
func (t SORT_TYPE) IsIn(targets ...SORT_TYPE) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t SORT_TYPE) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *SORT_TYPE) UnmarshalJSON(b []byte) error {
	ins, err := ParseSORT_TYPEFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
